name: CI/CD Pipeline

on: [push, pull_request]  # Триггеры для запуска

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последний Ubuntu
    
    steps:
    - uses: actions/checkout@v3  # Клонируем репозиторий
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run linter (flake8)
      run: flake8 .
    
    - name: Run tests
      run: python -m unittest discover tests